name: Tests

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - website/**

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    name: Tests
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['14', '16', '18']
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@56337c425554a6be30cdef71bf441f15be286854 # v3
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
      - name: Installation
        run: yarn
      - name: Test
        run: yarn test
      - name: TypeCheck website
        run: yarn workspace website typecheck
